In [1]:
import numpy as np
import math

In [2]:
file_name='input.txt'
outputfile_name='output.txt'
def open_file(file_name):
    A=[]
    with open(file_name,"r") as file:
        n=int(file.readline()[0])
        for _ in range(n):
            line=file.readline()[:-1]
            A.append(list(map(lambda x:float(x),line.split(" "))))
    return np.array(A) 
A=open_file(file_name)

In [3]:
A

array([[2., 4.],
       [1., 3.],
       [0., 0.],
       [0., 0.]])

In [4]:
def danhilepski(A):
    v=[]
    n,_=A.shape
    i=n-1
    m=n-1
    back=np.eye(n)
    while i>0:
        
        if A[i,i-1]!=0:
            M=np.eye(m+1)
            M[i-1,:]=A[i,:]
            M1=np.eye(m+1)
            M1[i-1,:]=-A[i,:]/A[i,i-1]
            M1[i-1,i-1]=1/A[i,i-1]
            back=back@M1
            A=M@A@M1
            
        else:
            non=False
            for j in range(i-1):                
                if A[i,j]!=0:
                    tempt=A[i-1,:]
                    A[i-1,:]=A[j,:]
                    A[j,:]=tempt
                    tempt=A[:,i-1]
                    A[:,i-1]=A[:,j]
                    A[:,j]=tempt
                    tempt=back[:,i-1]
                    back[:,i-1]=back[:,j]
                    back[:,j]=tempt
                    non=True
                    i+=1
                    break
            
            if non == False:
                for j in range(i,m):
                    M = np.eye(m+1)
                    M[:i, j+1] = -A[:i, j]
                    M1 = np.eye(m+1);
                    M1[:i, j+1] = A[:i, j]
                    A = M@A@M1
                    back = back@M1
          
                tt = False
                for j in range(i-1,-1,-1):               
                    if A[j, m] != 0:
                        M = np.eye(m+1)
                        x = M[i:m+1, :]
                        y = M[i-1, :]
                        M = np.vstack((M[:i-1, :], x, y))
                        M1 = M.T
                        A = M@A@M1
                        back = back@M1
                        i = m+1
                        tt = True
                        break
                if tt == False:
                    X = A[i:m+1, i:m+1]
                    k,_ = X.shape
                    v = findvalue(X)
                    
                    m = i-1
                    A = A[:m+1, :m+1]
                    back = np.eye(m+1)
            
                
        i-=1
    X=A[i:m+1,i:m+1]
    
    p=findvalue(X)
    
    k,_=X.shape
    
    u=np.eye(n)
    for i in range(len(p)):
        gt=1
        y=[1]
        for j in range(k-1):
            gt=gt*p[i]
            y.append(gt)
        y.reverse()
        y=np.array(y).reshape(-1,1)
        
        y=back@y
        y=y/sumsquare(y)
        
        u[:len(y),i]=y.reshape(-1)
        
      
    return A,p,u
    
def findvalue(A):
    p=-A[0,:]
    u=np.hstack((1,p))
    u=np.roots(u)
    return u
def sumsquare(y):
    tong=0
    for i in range(len(y)):
        tong+=y[i]**2
    return np.sqrt(tong)
def SVD(A):
    _,p,v=danhilepski(A.T@A)
    m,n=A.shape
    U=np.eye(m)
    sigma=np.zeros((m,n))
    V=np.eye(n)
    for i in range(len(v)):
        if i==0:
            V[:,i]=-v[:,i]
        else :         
            V[:,i]=v[:,i]
    for i in range(min(len(U),len(V))):
        U[i,:]=(A@V[:,i])/(np.sqrt(p[i]))
    for i in range(len(p)):
        sigma[i,i]=np.sqrt(p[i])
    with open(outputfile_name,'w') as f:
        f.write('U = ')
        np.savetxt(outputfile_name,U)
        f.write('\n')
        f.write('Sigma = ')
        np.savetxt(outputfile_name,sigma)
        f.write('\n')
        f.write('V.T = ')
        np.savetxt(outputfile_name,V)
        f.close()
    return U,sigma,V
    
            
        
       
    

In [6]:
U,sigma,V=SVD(A)

In [7]:
print(U)
print(sigma)
print(V)

[[-0.81741556 -0.57604844  0.          0.        ]
 [-0.57604844  0.81741556  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]
[[5.4649857  0.        ]
 [0.         0.36596619]
 [0.         0.        ]
 [0.         0.        ]]
[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]


In [8]:
a,b,c=np.linalg.svd(A)
np.linalg.svd(A)

(array([[-0.81741556, -0.57604844,  0.        ,  0.        ],
        [-0.57604844,  0.81741556,  0.        ,  0.        ],
        [ 0.        ,  0.        ,  1.        ,  0.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([5.4649857 , 0.36596619]),
 array([[-0.40455358, -0.9145143 ],
        [-0.9145143 ,  0.40455358]]))

In [9]:
A.T@A

array([[ 5., 11.],
       [11., 25.]])